### ISSUE TITLE
Failure to run lab - issues with auth header and agent jar file 

### ISSUE THREAD

**Issue by vikasphonsa** [rstatsinger/IASTRASPLab#1]
Hello,

Thanks for building this lab. I tried to run contrast agent with Webgoat following the instructions on https://github.com/rstatsinger/IASTRASPLab/blob/master/CESetup.md. But failed. Faced two issues

1. I couldn't find an Authorization Header under settings/api in the community edition. Has that been replaced by something else ? Perhaps Agent Username ?

2. While running docker I ran into the following error. 
_sudo docker run --rm -p 8080:8080 -t dockerwebgoat
Error opening zip file or JAR manifest missing : /opt/contrast/contrast.jar
Error occurred during initialization of VM
agent library failed to init: instrument_

I am on a Kali Linux VM and /opt/contrast/contrast.jar exists on it. 

Any ideas ? Thanks in advance. 

-Vik

**Comment by rstatsinger** [comment]
Hi Vikas –

Thanks for reaching out. The tokens you need – including the Authorization Header - are on your Profile page on the right side. Look for Personal Keys – under that is the Service Key and the Authorization header. Hit the Copy button to copy it:

[cid:image001.png@01D6B673.CE4522E0]

Your Docker build won’t work until you’ve properly authenticated to Contrast because you won’t have downloaded the contrast.jar file.

Hope this helps. Please keep me apprised of your progress!

Regards,

            Robert Statsinger
--
ROBERT STATSINGER<mailto:robert.statsinger@contrastsecurity.com> | Senior Solutions Architect
Contrast Security, Inc.<http://contrastsecurity.com/>  | Seamlessly Weave Application Security across the SDLC
<https://www.contrastsecurity.com/>+1-831-421-2760 (mobile)
Self-schedule a meeting with me: https://calendly.com/robert-statsinger-contrastsecurity

**Comment by vikasphonsa** [comment]
Hi Robert - Yes I had looked under Profile. Attaching screenshot of what I see. Couldn't find anything called Authorization Header. Organizational Settings is the only place that has the keys. If you had attached a screenshot, I couldn't see it. 

>>>Your Docker build won’t work until you’ve properly authenticated to Contrast because you won’t have downloaded the contrast.jar file.

Would manually downloading contrast.jar ( following the Add Agent workflow ) help with authentication ? I did that. Or does docker build have to authenticate ? 

<img width="1259" alt="contrast_settings" src="https://user-images.githubusercontent.com/942247/98577762-43dae580-2271-11eb-8a4e-4516bd78821b.png">

**Comment by rstatsinger** [comment]
Hi Vikas –

You are looking at the organization level API tokens. Click under your name at the top right to find your personal user settings and Profile, which contain your personal API tokens.

            Robert

--
ROBERT STATSINGER<mailto:robert.statsinger@contrastsecurity.com> | Senior Solutions Architect
Contrast Security, Inc.<http://contrastsecurity.com/>  | Seamlessly Weave Application Security across the SDLC
<https://www.contrastsecurity.com/>+1-831-421-2760 (mobile)
Self-schedule a meeting with me: https://calendly.com/robert-statsinger-contrastsecurity

**Comment by vikasphonsa** [comment]
facepalm. sorry about that. I looked multiple times, but the personal keys were below the fold of the webpage on my laptop and I missed them. found them.

**Comment by vikasphonsa** [comment]
Hi Robert - Using the right key and auth header, it worked. WebGoat loaded locally and showed up in the Contrast CE Portal. Thanks a lot sir. Closing the issue.

**Comment by rstatsinger** [comment]
Excellent – thanks for sticking with it Vikas. I hope you will follow the lab guide and send me some screen shots of your results.

Regards,

            Robert Statsinger

--
ROBERT STATSINGER<mailto:robert.statsinger@contrastsecurity.com> | Senior Solutions Architect
Contrast Security, Inc.<http://contrastsecurity.com/>  | Seamlessly Weave Application Security across the SDLC
<https://www.contrastsecurity.com/>+1-831-421-2760 (mobile)
Self-schedule a meeting with me: https://calendly.com/robert-statsinger-contrastsecurity

**Comment by vikasphonsa** [comment]
I tried. Ran into two issues

1. Contrast CE portal never reported more than 14 vulnerabilities that it showed as soon as I log into WebGoat. The XXE and SQLi vulns never show up even though I tried multiple times in WebGoat. 
2. The app in Contrast portal shows as offline after about 5 minutes, even though it is running in local docker and I am interacting with it. I've restarted docker a couple of times. Same results. It starts as online, shows 14 vulns, no other vulns show up and the app goes offline after a few minutes. 

I'll retry later in the day. Thanks. 

<img width="1280" alt="Screen Shot 2020-11-09 at 11 23 05 AM" src="https://user-images.githubusercontent.com/942247/98586993-63c4d600-227e-11eb-9a95-c37d46b5273d.png">

**Comment by rstatsinger** [comment]
Thanks Vikas. Can you contact support@contrastsecurity.com<mailto:support@contrastsecurity.com> on this?

            Robert

--
ROBERT STATSINGER<mailto:robert.statsinger@contrastsecurity.com> | Senior Solutions Architect
Contrast Security, Inc.<http://contrastsecurity.com/>  | Seamlessly Weave Application Security across the SDLC
<https://www.contrastsecurity.com/>+1-831-421-2760 (mobile)
Self-schedule a meeting with me: https://calendly.com/robert-statsinger-contrastsecurity

**Comment by vikasphonsa** [comment]
ok. will give it another shot to rule out user error :-) and then contact them. appreciate your help.
